const SHARKS=[
{name:"Great white shark",latin:"Carcharodon carcharias",emoji:"🦈",size:"Up to ~6 m documented",diet:"Fish, rays, marine mammals and carrion, varying with age and region.",habitat:"Temperate and subtropical coastal/offshore waters.",facts:"Great whites have a broad global distribution and are powerful, highly mobile predators.",tags:["giant","coastal"]},
{name:"Whale shark",latin:"Rhincodon typus",emoji:"🐋",size:"Up to ~18 m reported",diet:"Filter-feeds on plankton, fish eggs and small organisms.",habitat:"Warm and temperate oceans.",facts:"The largest living fish. Its feeding strategy is fundamentally different from that of predatory sharks.",tags:["giant"]},
{name:"Shortfin mako",latin:"Isurus oxyrinchus",emoji:"⚡",size:"Can exceed 4 m",diet:"Fast-swimming predator of fish and squid.",habitat:"Open ocean, generally warmer and temperate waters.",facts:"Among the fastest sharks, with a streamlined body adapted to active pursuit.",tags:["fast"]},
{name:"Hammerhead shark",latin:"Sphyrnidae",emoji:"🔨",size:"Varies by species; some exceed 3 m",diet:"Fish, squid, crustaceans and rays depending on species.",habitat:"Coastal and offshore tropical/temperate waters.",facts:"The expanded head shape may provide sensory and hydrodynamic advantages; hammerhead species differ substantially.",tags:["coastal"]},
{name:"Tiger shark",latin:"Galeocerdo cuvier",emoji:"🐯",size:"Often 3–5 m",diet:"Fish, turtles, birds, cephalopods, carrion and other prey.",habitat:"Tropical and warm-temperate coastal/open waters.",facts:"A broad-diet predator with distinctive vertical markings that are strongest in younger animals.",tags:["coastal","giant"]},
{name:"Greenland shark",latin:"Somniosus microcephalus",emoji:"❄️",size:"Up to ~7 m reported",diet:"Fish, marine mammals, carrion and other available prey.",habitat:"Cold North Atlantic and Arctic waters, including deep water.",facts:"Extremely slow-growing; research suggests exceptional longevity.",tags:["giant","deep"]},
{name:"Goblin shark",latin:"Mitsukurina owstoni",emoji:"👺",size:"Up to ~4–5 m reported",diet:"Deep-sea fish and other prey.",habitat:"Deep continental slopes and other deep ocean habitats.",facts:"Its highly protrusible jaws can shoot forward to seize prey.",tags:["deep"]},
{name:"Nurse shark",latin:"Ginglymostoma cirratum",emoji:"🌙",size:"Often 2–3 m",diet:"Bottom-dwelling fish, crustaceans and mollusks.",habitat:"Warm shallow coastal waters and reefs.",facts:"Often rests on the seafloor and can pump water across its gills while stationary.",tags:["coastal"]},
{name:"Blue shark",latin:"Prionace glauca",emoji:"🔵",size:"Can exceed 3 m",diet:"Fish, squid and carrion.",habitat:"Open ocean from tropical to cool waters.",facts:"A highly migratory pelagic shark known for long-distance movements.",tags:["fast"]},
{name:"Cookiecutter shark",latin:"Isistius brasiliensis",emoji:"🍪",size:"Around 50 cm",diet:"Cuts circular plugs from larger animals; also eats smaller prey.",habitat:"Deep ocean, with vertical migrations in some regions.",facts:"Tiny but unusual: it uses specialized lower teeth to remove neat circular bites.",tags:["deep"]},
{name:"Basking shark",latin:"Cetorhinus maximus",emoji:"🌊",size:"Can exceed 10 m",diet:"Filter-feeds on plankton.",habitat:"Temperate coastal and offshore waters.",facts:"The second-largest living fish and a harmless filter feeder.",tags:["giant"]},
{name:"Bull shark",latin:"Carcharhinus leucas",emoji:"🏞️",size:"Up to ~3.5 m reported",diet:"Fish, rays and other available prey.",habitat:"Coastal waters, estuaries and some freshwater systems.",facts:"Notable for its tolerance of low-salinity water and ability to travel into rivers.",tags:["coastal"]}
];

function initNav(){const b=document.querySelector(".menu-toggle"),n=document.querySelector(".nav");if(b)b.addEventListener("click",()=>n.classList.toggle("open"))}
function initSpecies(){const grid=document.querySelector("#species-grid");if(!grid)return;const search=document.querySelector("#species-search"),filters=document.querySelector("#filters");let filter="all";
function render(){const q=(search.value||"").toLowerCase().trim();grid.innerHTML="";const list=SHARKS.filter(s=>(filter==="all"||s.tags.includes(filter))&&(`${s.name} ${s.latin} ${s.diet} ${s.habitat} ${s.facts}`).toLowerCase().includes(q));if(!list.length){grid.innerHTML='<p class="no-results">No species match that search.</p>';return}list.forEach(s=>{const el=document.createElement("article");el.className="species-card";el.tabIndex=0;el.innerHTML=`<span class="species-emoji">${s.emoji}</span><h2>${s.name}</h2><div class="latin">${s.latin}</div><p>${s.facts}</p><div class="tags">${s.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div>`;el.addEventListener("click",()=>openSpecies(s));el.addEventListener("keydown",e=>{if(e.key==="Enter")openSpecies(s)});grid.appendChild(el)})}
function openSpecies(s){const modal=document.querySelector("#species-modal"),content=document.querySelector("#modal-content");content.innerHTML=`<div class="species-emoji">${s.emoji}</div><p class="kicker">SPECIES PROFILE</p><h2>${s.name}</h2><div class="latin">${s.latin}</div><div class="modal-stat"><div><b>Size</b><span>${s.size}</span></div><div><b>Habitat</b><span>${s.habitat}</span></div></div><h3>Diet</h3><p>${s.diet}</p><h3>What stands out?</h3><p>${s.facts}</p>`;modal.hidden=false}
document.querySelector(".modal-close")?.addEventListener("click",()=>document.querySelector("#species-modal").hidden=true);document.querySelector("#species-modal")?.addEventListener("click",e=>{if(e.target.id==="species-modal")e.currentTarget.hidden=true});search.addEventListener("input",render);filters.addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;filters.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});render()}
function initAnatomy(){const info=document.querySelector("#anatomy-info");if(!info)return;const parts={gills:["Gills","Most sharks extract oxygen from water passing over gill tissues. Different species use different methods to ventilate their gills."],electro:["Electroreception","Ampullae of Lorenzini are jelly-filled sensory organs that detect weak electrical fields. They are especially useful for close-range prey detection and orientation."],teeth:["Teeth","Tooth form reflects feeding ecology. Many sharks continuously replace teeth as older teeth are lost."],skin:["Dermal denticles","Shark skin is covered in tiny tooth-like structures. They contribute to the rough texture and influence water flow along the body."],lateral:["Lateral line","A network of sensory cells detects local water movement and vibrations, helping a shark respond to nearby motion."],fins:["Fins","Dorsal, pectoral, pelvic and caudal fins stabilize, steer and propel the shark. Their shapes vary with lifestyle."]};document.querySelectorAll(".hotspot").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".hotspot").forEach(x=>x.classList.remove("active"));b.classList.add("active");const [title,text]=parts[b.dataset.part];info.innerHTML=`<p class="kicker">ANATOMY ${b.textContent}</p><h2>${title}</h2><p>${text}</p>`}))}
function initQuiz(){const q=document.querySelector("#question");if(!q)return;const data=[{q:"Which shark is the largest living fish?",a:["Great white","Whale shark","Tiger shark","Mako"],c:1,e:"Whale sharks are the largest living fish and filter-feed."},{q:"What do ampullae of Lorenzini detect?",a:["Light","Electrical fields","Sound only","Salinity only"],c:1,e:"They detect weak electrical fields in seawater."},{q:"Which shark is famous for protrusible jaws?",a:["Goblin shark","Nurse shark","Blue shark","Basking shark"],c:0,e:"Goblin sharks can rapidly extend their jaws to capture prey."},{q:"What does the lateral line detect?",a:["Water movement","Blood pressure","UV light","Magnetism only"],c:0,e:"The lateral line senses water movement and vibration."},{q:"Which is true?",a:["All sharks live in warm water","Sharks are mammals","Some sharks filter-feed","Sharks have bony skeletons"],c:2,e:"Whale sharks and basking sharks are filter feeders; sharks are cartilaginous fishes."}];let i=0,score=0,answered=false;const answers=document.querySelector("#answers"),feedback=document.querySelector("#feedback"),next=document.querySelector("#next"),count=document.querySelector("#quiz-count"),scoreEl=document.querySelector("#quiz-score"),progress=document.querySelector("#quiz-progress");function show(){const x=data[i];answered=false;feedback.hidden=true;next.disabled=true;count.textContent=`Question ${i+1} of ${data.length}`;scoreEl.textContent=`Score ${score}`;progress.style.width=`${(i/data.length)*100}%`;q.textContent=x.q;answers.innerHTML="";x.a.forEach((a,j)=>{const b=document.createElement("button");b.className="answer";b.type="button";b.textContent=a;b.addEventListener("click",()=>{if(answered)return;answered=true;next.disabled=false;if(j===x.c){score++;b.classList.add("correct");feedback.textContent="Correct — "+x.e}else{b.classList.add("wrong");answers.children[x.c].classList.add("correct");feedback.textContent="Not quite — "+x.e}feedback.hidden=false;scoreEl.textContent=`Score ${score}`;progress.style.width=`${((i+1)/data.length)*100}%`});answers.appendChild(b)})}next.addEventListener("click",()=>{if(i<data.length-1){i++;show()}else{q.textContent=`Finished — ${score}/${data.length}`;answers.innerHTML="";feedback.hidden=false;feedback.textContent=score===data.length?"Perfect score. You know your sharks.":"Nice work. Explore the atlas and try again.";next.textContent="Restart quiz";next.disabled=false;next.onclick=()=>{i=0;score=0;next.textContent="Next question";next.onclick=null;show()}}});show()}
document.addEventListener("DOMContentLoaded",()=>{initNav();initSpecies();initAnatomy();initQuiz()});